name: Deploy Coscine Static Site to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource-name: 
          - DhakanDB_2019
          - BommanaS_2023
          - BackhedF_2015
          - ChngKR_2016
          - DeFilippisF_2019
          - BaruchEN_2021
          - ContevilleLC_2019
          - FanY_2023
          - BritoIL_2016
          - BoktorJC_2023
          - CosteaPI_2017
          - DavidLA_2015
          - Bengtsson-PalmeJ_2015
          - AverinaOV_2020
          - FerrettiP_2018
          - AsnicarF_2017
          - DavarD_2021
          - ChuDM_2017
          - BedarfJR_2017
          - BaiX_2021
          - Castro-NallarE_2015
          - AsnicarF_2021
          - FengQ_2015
          - ChengpingW_2017
          - ArtachoA_2021
          - BrooksB_2017
    env:
      PROJECT_NAME: ${{ vars.COSCINE_PROJECT_NAME }}
      COSCINE_API_TOKEN: ${{ vars.COSCINE_API_TOKEN }}
    steps:
      - name: Check Python version
        run: python -V

      - name: Install git
        run: sudo apt install -y git

      - name: Clone repository
        run: git clone https://git.rwth-aachen.de/coscine/community-features/coscine-static-site-generator.git

      - name: Install requirements
        working-directory: ./coscine-static-site-generator/
        run: pip install -r requirements.txt

      - name: Build static site and generate navigation tabs
        working-directory: ./coscine-static-site-generator/
        run: |
          RESOURCE_NAMES=("DhakanDB_2019" "BommanaS_2023" "BackhedF_2015" "ChngKR_2016" "DeFilippisF_2019" "BaruchEN_2021" "ContevilleLC_2019" "FanY_2023" "BritoIL_2016" "BoktorJC_2023" "CosteaPI_2017" "DavidLA_2015" "Bengtsson-PalmeJ_2015" "AverinaOV_2020" "FerrettiP_2018" "AsnicarF_2017" "DavarD_2021" "ChuDM_2017" "BedarfJR_2017" "BaiX_2021" "Castro-NallarE_2015" "AsnicarF_2021" "FengQ_2015" "ChengpingW_2017" "ArtachoA_2021" "BrooksB_2017")

          # Generate static site for each resource
          for RESOURCE in "${RESOURCE_NAMES[@]}"; do
            echo "Processing resource: $RESOURCE"
            python -m src -t "$COSCINE_API_TOKEN" -p "$PROJECT_NAME" -r "$RESOURCE" -y -o ./public
          done

          # Generate dynamic navigation HTML
          HTML_NAV=""
          for RESOURCE in "${RESOURCE_NAMES[@]}"; do
            HTML_NAV+="<a class='tab' href='/public/$RESOURCE/index.html' target='_blank'>$RESOURCE</a>"
          done

          # Ensure the navigation.html file is placed in the correct directory
          echo "$HTML_NAV" > ./public/navigation.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
