name: Deploy Coscine Static Site to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ vars.COSCINE_PROJECT_NAME }}
      COSCINE_API_TOKEN: ${{ secrets.COSCINE_API_TOKEN }} 
    steps:
      - name: Check Python version
        run: python -V

      - name: Install git
        run: sudo apt install -y git

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy webpage
        run: |
          pwd
          mkdir -p public/
          dir
          cp index.html public/
          cp style.css public/
          cp coscine_logo.gif public/

      - name: Clone repository
        run: git clone https://git.rwth-aachen.de/coscine/community-features/coscine-static-site-generator.git

      - name: Install requirements
        working-directory: ./coscine-static-site-generator/
        run: pip install -r requirements.txt

      - name: Build static site and generate navigation tabs
        working-directory: ./coscine-static-site-generator/
        run: |
          RESOURCE_NAMES=("ArtachoA_2021" "AsnicarF_2017" "BackhedF_2015" "BaiX_2021" "BaruchEN_2021" "Bengtsson-PalmeJ_2015" "BoktorJC_2023" "ChengpingW_2017" "ChuDM_2017" "ContevilleLC_2019" "DavidLA_2015" "DeFilippisF_2019" "DhakanDB_2019" "FerrettiP_2018" "HeQ_2017" "HMP_2012" "HMP_2019_ibdmdb" "HMP_2019_t2d" "IaniroG_2022" "IjazUZ_2017" "JacobsonDK_2021" "JieZ_2017" "KarlssonFH_2013" "KaurK_2020" "KosticAD_2015" "LiuW_2016" "LokmerA_2019" "MejiaR_2020" "OsakunorDNM_2020" "PasolliE_2019" "PernigoniN_2021" "WampachL_2018" "YassourM_2018")
          
          # Generate static site for each resource
          for RESOURCE in "${RESOURCE_NAMES[@]}"; do
            echo "Processing resource: $RESOURCE"
            mkdir -p ../public/$RESOURCE
            python -m src -t "$COSCINE_API_TOKEN" -p "$PROJECT_NAME" -r "$RESOURCE" -y -o ../public/"$RESOURCE"
          done
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
